---
name: Deploy Collection

# Trigger the workflow however you prefer
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}"
